### ISSUE TITLE
Exercise 3: Records

### ISSUE THREAD

**Issue by JayLoomis** [JayLoomis/cornpython#1]
In this exercise, you'll work with the beginnings of a database-like structure. The program you're working toward is a customer contact list that tracks basic information about customers and your connections with them.

To start, make a program that:
-   Prompts the user to enter the following information for a customer contact list:
    -   Last name
    -   First name
    -   Phone number
    -   Email address
-   Stores the supplied information in a dictionary with appropriately named keys
-   Prints out the information in a format that looks good to you

**Comment by datapawn** [comment]
What do i do with "Issues?" - This part of the app is done and moved on to Revisions, so do I typically 'resolve' these somehow?

**Comment by JayLoomis** [comment]
When you've pushed it to GitHub and made a PR, link the PR over on the right here. Then we close out the PR we have the option of closing the issue as well.

I don't see any revisions on GitHub yet. At the very least, I'd like to see you clean this up so that it does what the requirements say and nothing more. Get rid of the extraneous files. Get rid of the employee database stuff and focus it on the customer contact list in the reqs.

**Comment by datapawn** [comment]
Let's go over how to do that tomorrow, so i'm not just poking at it from here.
