### ISSUE TITLE
Exercise 3.1

### ISSUE THREAD

**Issue by JayLoomis** [JayLoomis/cornpython#2]
Change your program created in exercise 3 to add a field to the record (item to the dictionary) that holds a list of contact records.

When the user contacts a customer, they will need to add that interaction to the customer record. Your dictionary should track a list of customer interactions, by making a new dictionary item that holds a list of interaction records. Each should have the date and time of the interaction and a note that the user enters.

Come up with an appropriate user interface whereby the user can add, view, or delete customer interactions from the customer record.

Make functions to perform the adding and deleting of customer interactions.

Use the standard Python datetime module to get the current time when the user adds a customer interaction. Decide the best way to store the datetime information in your list.

**Comment by datapawn** [comment]
If i'm understanding this correctly you want the contact time and notes to be a nested dictionary.  I'm having trouble with that, but also - is there a benefit to having it in that format?  part of me is having data-nerd problems with wanting to just add two new K,V pairs to the existing dictionary contactdate=(a datetime obj) and contactnotes=(a string obj).  Maybe there's more to dictionaries i need to learn?

**Comment by datapawn** [comment]
I should also note:  I'm having the hardest time finding a solution to "how do i add to a dictionary inside a dictionary?" - so this version of r1 is not yet fully functional, until I can find a way to add to a dictionary inside a dictionary.

**Comment by JayLoomis** [comment]
I think this is as done as it's gonna be, and you've moved on, so I'm closing it out.

Good job!
