### ISSUE TITLE
Little Poop 2.1: checking for powers

### ISSUE THREAD

**Issue by JayLoomis** [JayLoomis/cornpython#7]
Write a function that takes a positive integer as an argument and returns a Boolean indicating whether the argument is a power of three.

Hint: you might want to use recursion for this, which we haven't talked about yet. Exciting!

**Comment by JayLoomis** [comment]
For this second round of li'l poops, just build them into a single module. As you add a new function to module, add appropriate code to your module's main function to run it through its paces.

**Comment by datapawn** [comment]
Should i be making a new branch for this?  A little poops branch?
