### ISSUE TITLE
Little Poop 2.2: Anagrams

### ISSUE THREAD

**Issue by JayLoomis** [JayLoomis/cornpython#8]
Write a function that takes two strings and determines whether the second is an anagram of the first. Return an appropriate Boolean.

Because anagrams are often multiple words, remove all non-printing characters from both params before you do your check.

**Comment by JayLoomis** [comment]
Let's turn this poop into a little OOP!

Build a class named `Anagrammer`:
-   Create a constructor that takes one positional argument named `dict_file`,
    -   In the constructor, define an instance variable named `dictionary`.
        -   Open the file whose name was passed as `dict_file` and read its contents into the dictionary list
-   Create a static method named is_anagram:
    -   Use the function requirements from the original issue post above for this method.
-   Create an instance method named `find_anagram` that takes one parameter: `word`:
    -   `word` is the word for which to find an anagram
    -   Shuffle the dictionary list (there's a library function that does this, it's with the other random stuff)
    -   Find the first anagram in the shuffled dictionary and return it, searching for single-word anagrams only.
    -   If there is no anagram, return the original word
-   Create an instance method named `list_anagrams` that takes one parameter: `word`:
    -   `word` is the word for which to list the anagrams
    -   Sort the word dictionary
    -   Find all of the possible anagrams for `word`, searching for single-word anagrams only 
    -   Return a sorted list of all the anagrams you found, or a list containing only the original word if there are none

Build a simple UI that surfaces all of the functionality of  the `Anagrammer` class to the user. You decide whether you want to make a single-instance class to do the UI work, or to do it procedural style. In either case, you'll make a single instance of `Anagrammer` to use.

**Considerations**
-   Don't waste time trying to finding the perfect, most clever solution to finding anagrams! Get something that works, then
    improve it as you have time and inclination.
-   Think about why we're using an object for `Anagrammer`, since we'll only be using a single instance of it. There's at least one
    good reason.
-   Think about what it would take to:
    -   Find multi-word anagrams
    -   Filter the dictionary list to quickly get to a list that's worth the effort of a deeper comparison

**Comment by JayLoomis** [comment]
I've added a dictionary text file `dictionary.txt` to the little poops directory on main. Use this for all your English words needs. 

I got this from http://wordlist.aspell.net/12dicts/

It's the v6.0.2, Amercian word list2of12inf.txt, with the dubious plural forms removed. You don't need to know all that, but I might like to use it again somewhere, so I wanted to have a record of provenance.

**Comment by datapawn** [comment]
This is so close to a PR, but something in the find_anagram function is going incomprehensibly weird.

I know it's not:
* that the shuffled dictionary has anymore \n
* that the shuffled dictionary is incomplete

is_anagram is working fine, and list_anagram is working delightfully.  But something in the logic of find_anagram is just mysteriously incapable of seeing results.  I tried switching from an empty string to a list, and i tried iterating on i / range(len()).  nothing worked!

**Comment by JayLoomis** [comment]
This looks fine. Closing.
